server:
  port: 9004

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/paystream_neft
    #url: jdbc:postgresql://postgres:5432/paystream_neft
    username: ${NEFT_DB_USERNAME:postgres}
    password: ${NEFT_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    baseline-on-migrate: true
    baseline-version: 1

  kafka:
    bootstrap-servers: localhost:29092
    #bootstrap-servers: kafka:9092

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

resilience4j:
  circuitbreaker:
    instances:
      account-service:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
  retry:
    instances:
      account-service:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - feign.FeignException
