server:
  port: 9007

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paystream_upi
    #url: jdbc:postgresql://postgres:5432/paystream_upi
    username: ${UPI_DB_USERNAME}
    password: ${UPI_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: localhost
      #host: redis-master
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    #bootstrap-servers: kafka:9092

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      account-service:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
  retry:
    instances:
      account-service:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - feign.FeignException
