namespace: paystream-staging
replicaCount: 2

resources:
  requests:
    cpu: 250m
    memory: 384Mi
  limits:
    cpu: 500m
    memory: 512Mi

hpa:
  minReplicas: 2
  maxReplicas: 4

pdb:
  minAvailable: 1
