server:
  port: 9005   # change for each service

spring:
  application:
    name: notification-service

  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
