{{- if and .Values.pdb.enabled (gt (int .Values.pdb.minAvailable) 0) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "paystream-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "paystream-service.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
{{- end }}
