apiVersion: v1
kind: Service
metadata:
  name: {{ include "paystream-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "paystream-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.serviceName }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
