apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: paystream-app-secrets
  namespace: paystream-dev
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "paystream/dev/app-secrets"
        objectType: "secretsmanager"
        jmesPath:
          - path: "ACCOUNT_DB_USERNAME"
            objectAlias: "ACCOUNT_DB_USERNAME"
          - path: "ACCOUNT_DB_PASSWORD"
            objectAlias: "ACCOUNT_DB_PASSWORD"
          - path: "NEFT_DB_USERNAME"
            objectAlias: "NEFT_DB_USERNAME"
          - path: "NEFT_DB_PASSWORD"
            objectAlias: "NEFT_DB_PASSWORD"
          - path: "RTGS_DB_USERNAME"
            objectAlias: "RTGS_DB_USERNAME"
          - path: "RTGS_DB_PASSWORD"
            objectAlias: "RTGS_DB_PASSWORD"
          - path: "IMPS_DB_USERNAME"
            objectAlias: "IMPS_DB_USERNAME"
          - path: "IMPS_DB_PASSWORD"
            objectAlias: "IMPS_DB_PASSWORD"
          - path: "UPI_DB_USERNAME"
            objectAlias: "UPI_DB_USERNAME"
          - path: "UPI_DB_PASSWORD"
            objectAlias: "UPI_DB_PASSWORD"
          - path: "TRANSACTION_DB_USERNAME"
            objectAlias: "TRANSACTION_DB_USERNAME"
          - path: "TRANSACTION_DB_PASSWORD"
            objectAlias: "TRANSACTION_DB_PASSWORD"
          - path: "FRAUD_DB_USERNAME"
            objectAlias: "FRAUD_DB_USERNAME"
          - path: "FRAUD_DB_PASSWORD"
            objectAlias: "FRAUD_DB_PASSWORD"
          - path: "AUDIT_DB_USERNAME"
            objectAlias: "AUDIT_DB_USERNAME"
          - path: "AUDIT_DB_PASSWORD"
            objectAlias: "AUDIT_DB_PASSWORD"
          - path: "AUTH_DB_USERNAME"
            objectAlias: "AUTH_DB_USERNAME"
          - path: "AUTH_DB_PASSWORD"
            objectAlias: "AUTH_DB_PASSWORD"
          - path: "CUSTOMER_DB_USERNAME"
            objectAlias: "CUSTOMER_DB_USERNAME"
          - path: "CUSTOMER_DB_PASSWORD"
            objectAlias: "CUSTOMER_DB_PASSWORD"
          - path: "NOTIFICATION_DB_USERNAME"
            objectAlias: "NOTIFICATION_DB_USERNAME"
          - path: "NOTIFICATION_DB_PASSWORD"
            objectAlias: "NOTIFICATION_DB_PASSWORD"
          - path: "API_KEY"
            objectAlias: "API_KEY"
      - objectName: "paystream/dev/legacy-keystore-passwords"
        objectType: "secretsmanager"
        jmesPath:
          - path: "JWT_KEYSTORE_PASSWORD"
            objectAlias: "JWT_KEYSTORE_PASSWORD"
          - path: "JWT_KEY_PASSWORD"
            objectAlias: "JWT_KEY_PASSWORD"
          - path: "KEYSTORE_STORE_PASSWORD"
            objectAlias: "KEYSTORE_STORE_PASSWORD"
          - path: "KEYSTORE_KEY_PASSWORD"
            objectAlias: "KEYSTORE_KEY_PASSWORD"
  secretObjects:
    - secretName: paystream-secrets
      type: Opaque
      data:
        - objectName: "ACCOUNT_DB_USERNAME"
          key: "ACCOUNT_DB_USERNAME"
        - objectName: "ACCOUNT_DB_PASSWORD"
          key: "ACCOUNT_DB_PASSWORD"
        - objectName: "NEFT_DB_USERNAME"
          key: "NEFT_DB_USERNAME"
        - objectName: "NEFT_DB_PASSWORD"
          key: "NEFT_DB_PASSWORD"
        - objectName: "RTGS_DB_USERNAME"
          key: "RTGS_DB_USERNAME"
        - objectName: "RTGS_DB_PASSWORD"
          key: "RTGS_DB_PASSWORD"
        - objectName: "IMPS_DB_USERNAME"
          key: "IMPS_DB_USERNAME"
        - objectName: "IMPS_DB_PASSWORD"
          key: "IMPS_DB_PASSWORD"
        - objectName: "UPI_DB_USERNAME"
          key: "UPI_DB_USERNAME"
        - objectName: "UPI_DB_PASSWORD"
          key: "UPI_DB_PASSWORD"
        - objectName: "TRANSACTION_DB_USERNAME"
          key: "TRANSACTION_DB_USERNAME"
        - objectName: "TRANSACTION_DB_PASSWORD"
          key: "TRANSACTION_DB_PASSWORD"
        - objectName: "FRAUD_DB_USERNAME"
          key: "FRAUD_DB_USERNAME"
        - objectName: "FRAUD_DB_PASSWORD"
          key: "FRAUD_DB_PASSWORD"
        - objectName: "AUDIT_DB_USERNAME"
          key: "AUDIT_DB_USERNAME"
        - objectName: "AUDIT_DB_PASSWORD"
          key: "AUDIT_DB_PASSWORD"
        - objectName: "AUTH_DB_USERNAME"
          key: "AUTH_DB_USERNAME"
        - objectName: "AUTH_DB_PASSWORD"
          key: "AUTH_DB_PASSWORD"
        - objectName: "CUSTOMER_DB_USERNAME"
          key: "CUSTOMER_DB_USERNAME"
        - objectName: "CUSTOMER_DB_PASSWORD"
          key: "CUSTOMER_DB_PASSWORD"
        - objectName: "NOTIFICATION_DB_USERNAME"
          key: "NOTIFICATION_DB_USERNAME"
        - objectName: "NOTIFICATION_DB_PASSWORD"
          key: "NOTIFICATION_DB_PASSWORD"
        - objectName: "JWT_KEYSTORE_PASSWORD"
          key: "JWT_KEYSTORE_PASSWORD"
        - objectName: "JWT_KEY_PASSWORD"
          key: "JWT_KEY_PASSWORD"
        - objectName: "KEYSTORE_STORE_PASSWORD"
          key: "KEYSTORE_STORE_PASSWORD"
        - objectName: "KEYSTORE_KEY_PASSWORD"
          key: "KEYSTORE_KEY_PASSWORD"
        - objectName: "API_KEY"
          key: "API_KEY"
