serviceName: account-service
image:
  repository: 198758256599.dkr.ecr.ap-south-1.amazonaws.com/account-service
  tag: "latest"
containerPort: 9003

extraEnv:
  SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-dev:5432/paystream_accounts"
