server:
  port: 0   # dynamic port for Eureka

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:mysql://localhost:3306/flipkart_inventory?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: "{cipher}90644e320bf5e563200689802982e6fa5ff4c7f30974a81fbd0eb954da5d6530"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092   # ⚠️ change to kafka:9092 if Docker

    consumer:
      group-id: inventory-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh

logging:
  level:
    org.apache.kafka: INFO
    org.springframework.kafka: INFO