apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: paystream
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-role
  namespace: paystream
rules:
  - apiGroups: ["", "apps", "autoscaling", "networking.k8s.io"]
    resources:
      - deployments
      - services
      - pods
      - pods/log
      - configmaps
      - ingresses
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-rolebinding
  namespace: paystream
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: paystream
roleRef:
  kind: Role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io
