CREATE TABLE products (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                          title VARCHAR(255) NOT NULL,
                          brand VARCHAR(255) NOT NULL,

                          description VARCHAR(2000) NOT NULL,
                          image_url VARCHAR(255),

                          price DOUBLE PRECISION NOT NULL,
                          discount DOUBLE PRECISION,
                          rating DOUBLE PRECISION,

                          stock INTEGER NOT NULL,

                          category_id BIGINT NOT NULL,

                          deleted BOOLEAN NOT NULL DEFAULT FALSE,
                          version BIGINT NOT NULL DEFAULT 0,

                          created_at TIMESTAMP,
                          updated_at TIMESTAMP
);
