CREATE TABLE product_variants (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                  variant_name VARCHAR(255),
                                  variant_value VARCHAR(255),

                                  additional_price DOUBLE PRECISION,

                                  product_id BIGINT
);
