CREATE TABLE review (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                        comment VARCHAR(2000) NOT NULL,
                        rating INTEGER NOT NULL,

                        user_id BIGINT,
                        product_id BIGINT,

                        created_at TIMESTAMP
);
