apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: flipkart
data:
  SPRING_PROFILES_ACTIVE: "docker"
  SPRING_APPLICATION_NAME: "product-service"
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
  SPRING_CLOUD_CONFIG_URI: "http://config-server:8888"
  AWS_REGION: "ap-south-1"
  AWS_S3_BUCKET: "flipkart-clone-products"
